### ISSUE TITLE
MaxRepairCost v2.12 generated an exception while executing task 17

### ISSUE THREAD

**Issue by Devaxtion** [Geeveloper/MaxRepairCost#3]
**Server Version**
Paper version git-Paper-123 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

**Plugin Version**
v.2.120

**Describe the bug**
```
04.07 17:13:02 [Server] WARN [MaxRepairCost] Plugin MaxRepairCost v2.12 generated an exception while executing task 17
04.07 17:13:02 [Server] INFO java.lang.IllegalStateException: InventoryCloseEvent may only be triggered synchronously.
04.07 17:13:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:524) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1336) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.closeInventory(EntityPlayer.java:1252) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:622) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at me.geekles.repaircost.checks.ModeCheck.terminate(ModeCheck.java:31) ~[?:?]
04.07 17:13:02 [Server] INFO at me.geekles.repaircost.checks.ModeCheck.update(ModeCheck.java:47) ~[?:?]
04.07 17:13:02 [Server] INFO at me.geekles.repaircost.checks.ModeCheckManager$CheckRunnable.lambda$run$0(ModeCheckManager.java:85) ~[?:?]
04.07 17:13:02 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_191]
04.07 17:13:02 [Server] INFO at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_191]
04.07 17:13:02 [Server] INFO at me.geekles.repaircost.checks.ModeCheckManager$CheckRunnable.run(ModeCheckManager.java:85) ~[?:?]
04.07 17:13:02 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
04.07 17:13:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
04.07 17:13:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
04.07 17:13:02 [Server] WARN [MaxRepairCost] Plugin MaxRepairCost v2.12 generated an exception while executing task 17
04.07 17:13:02 [Server] INFO java.lang.IllegalStateException: InventoryCloseEvent may only be triggered synchronously.
04.07 17:13:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:524) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1336) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.closeInventory(EntityPlayer.java:1252) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:622) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at me.geekles.repaircost.checks.ModeCheck.terminate(ModeCheck.java:31) ~[?:?]
04.07 17:13:02 [Server] INFO at me.geekles.repaircost.checks.ModeCheck.update(ModeCheck.java:47) ~[?:?]
04.07 17:13:02 [Server] INFO at me.geekles.repaircost.checks.ModeCheckManager$CheckRunnable.lambda$run$0(ModeCheckManager.java:85) ~[?:?]
04.07 17:13:02 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_191]
04.07 17:13:02 [Server] INFO at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_191]
04.07 17:13:02 [Server] INFO at me.geekles.repaircost.checks.ModeCheckManager$CheckRunnable.run(ModeCheckManager.java:85) ~[?:?]
04.07 17:13:02 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.3.jar:git-Paper-123]
04.07 17:13:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
04.07 17:13:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
04.07 17:13:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**To Reproduce**
I get this error (infinite errors) when I repair something. The server crashes.

**Comment by Geeveloper** [comment]
I apologize, there seemed to be an issue when I last updated the resource in uploading the jar. You can download now the update to date version of the resource from the spigot page. 
https://www.spigotmc.org/resources/maxrepaircost-%E2%98%85tool%E2%98%85-an-essential-change-for-anvils.62905/update?update=286068

**Comment by Devaxtion** [comment]
Thank you!!
