### ISSUE TITLE
NoSuchMethodException in PlaceholderItem.<init>

### ISSUE THREAD

**Issue by fafrd** [Geeveloper/MaxRepairCost#7]
**Server Version**
What spigot/paper/craftbukkit/etc. version are you using?

This server is running Paper version git-Paper-132 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Plugin Version**
What version of MaxRepairCost are you using?

latest, bab9f25

**Describe the bug**
The following exception is printed to the log:
```
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_15_R1.NBTTagString.<init>(java.lang.String)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at java.base/java.lang.Class.getConstructor0(Class.java:3349)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at java.base/java.lang.Class.getConstructor(Class.java:2151)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at me.geekles.repaircost.assets.items.PlaceholderItem.<init>(PlaceholderItem.java:51)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at me.geekles.repaircost.assets.items.PlaceholderItem.<init>(PlaceholderItem.java:60)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at me.geekles.repaircost.listeners.AnvilManagementListener.onAnvilPrepare(AnvilManagementListener.java:72)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1500)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.ContainerAnvil.e(ContainerAnvil.java:317)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.ContainerAnvil.a(ContainerAnvil.java:133)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.ContainerAnvil$1.update(ContainerAnvil.java:42)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:158)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.Slot.set(SourceFile:82)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.Container.a(Container.java:334)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2341)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
Mar 29 12:00:41 fuzz python3[11786]: [12:00:41 WARN]:         at java.base/java.lang.Thread.run(Thread.java:834) 
```

**Comment by Geeveloper** [comment]
Just released 1.15.2 support with my early beta release. Will be releasing an official release shortly on my spigot page to support a larger variety of versions. You can always go here, https://discord.gg/us8kcvG, for further support or to check out the early beta release.
